
### DB ###
spring:
  output:
    ansi:
      enabled: always
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${MYSQL_URL} #?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}
  ### 영상 크기 제한 ###
  servlet:
    multipart:
      maxFileSize: 30MB
      maxRequestSize: 30MB

### JPA ###
  jpa:
    database: mysql
    hibernate:
      ddl-auto: update #create, create-drop, none, update
      naming:
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy # set DB column name by snake case
    show-sql: true
    generate-ddl: true

### DB initialize auto insert ###
#  sql:
#    init:
#      mode: always
#      encoding: utf-8
#      # data-locations: "classpath: data.sql" #use different file for initializing data. default file is import.sql

  redis:
    host: ${REDIS_HOST}
    port: ${REDIS_PORT}
    password: ${REDIS_PASSWORD}

### S3 ###
cloud:
  aws:
    s3:
      bucket: ${AWS_S3_BUCKET_NAME}
    credentials:
      access-key: ${AWS_S3_ACCESS_KEY}
      secret-key: ${AWS_S3_SECRET_KEY}
    region:
      static: ap-northeast-2
      auto: false
    stack:
      auto: false

jwt:
  token:
    secretKey: ${JWT_TOKEN_SECRET_KEY}

### Firebase secret key (FCM) ###
firebase:
  secret-key:
    path: ${FIREBASE_SECRET_KEY_FILE_PATH}
#    json: ${FIREBASE_SECRET_KEY_JSON}