
// api 명 : h3
== *Send Play Skeleton*
스테이지 플레이 스켈레톤 전송

[.line-through]##ps.큰 수정 네번째는 하지 않게 도와주세여...##

- URL : `/app/stage/play/skeleton`

==== Request header
|===
|필드명|타입|필수여부|제약조건|설명
|`+x-access-token+`
|`+String+`
|true
|JWT 형식
|액세스 토큰
|===

==== Request fields
|===
|필드명|타입|필수여부|제약조건|설명
|`+playerNum+`
|`+Integer+`
|true
|공백 불가
|보낼 사용자의 플레이어 번호(CATCH_END 응답에서 받은 번호)
|`+frameNum+`
|`+Integer+`
|true
|공백 불가
|보낼 스켈레톤의 순서(프레임) 번호. 0부터 시작
|`+skeleton+`
|`+-+`
|false
|
|보낼 스켈레톤 데이터
|`+skeleton.0+`
|`+-+`
|false
|
|보낼 관절 객체 하나. 0~32 각 관절 인덱스 번호
|`+skeleton.0.type+`
|`+Integer+`
|false
|
|관절 인덱스 번호
|`+skeleton.0.x+`
|`+Double+`
|false
|
|관절 x 좌표
|`+skeleton.0.y+`
|`+Double+`
|false
|
|관절 y 좌표
|`+skeleton.0.z+`
|`+Double+`
|false
|
|관절 z 좌표
|`+skeleton.0.likelihood+`
|`+Double+`
|false
|
|가능도? 프론트에서 정해준거라 뭔지 몰라요..
|===

==== Request body
[source,options="wrap"]
----
$ _INFO_:send STOMP message, destination = /app/stage/play/skeleton, content =
{
    "playerNum" : 0,
    "frameNum" : 0,
    "skeleton" : {
        "0":  {
            "type": 0,
            "x": 91.00,
            "y": 253.00,
            "z": 395.12,
            "likelihood": 0.99
        },
        "1":  {
            "type": 1,
            "x": 91.00,
            "y": 253.00,
            "z": 395.12,
            "likelihood": 0.99
        },
//...
        "32": {
            "type": 32,
            "x": 91.00,
            "y": 253.00,
            "z": 395.12,
            "likelihood": 0.99
        }
    }
},
header = {"x-access-token" : "eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJkNmIwMjNhOC1mNTAyLTRmMWYtYWU2Yy1hODM4M2VjNmUyYTEiLCJyb2xlcyI6WyJST0xFX1VTRVIiXSwiaWF0IjoxNjkxMTU5NjI1LCJleHAiOjE2OTExNjMyMjV9.qgBY3mGpPDGfOFeJlVyN_OxnWUkrzzanRLezgNd7W_w"}
----

==== Response fields
|===
|필드명|타입|필수여부|설명
|`+timeStamp+`
|`+LocalDateTime+`
|true
|응답 시각
|`+type+`
|`+String+`
|true
|소켓 통신 유형. 고정값(PLAY_SKELETON)
|`+data.userId+`
|`+String+`
|true
|보낸 사용자 고유값
|`+data.playerNum+`
|`+Integer+`
|true
|보낸 사용자의 플레이어 번호(CATCH_END 응답에서 받은 번호)
|`+data.frameNum+`
|`+Integer+`
|true
|이 사용자가 보낸 스켈레톤 순서(프레임) 번호. 0부터 시작
|`+data.skeleton+`
|`+-+`
|false
|보낸 스켈레톤 데이터 (하위 형식 request field 와 동일)
|===

==== Response body
[source,http,options="nowrap"]
----
$ _INFO_:Receive subscribed message from destination /topic/stage, content = MESSAGE
content-length:699
message-id:3f017a8a-ec17-26fe-57cf-536d851ee8ec-22
subscription:sub-0
content-type:application/json
destination:/topic/stage
content-length:699

{
    "timeStamp":"2023/08/04 23:41:06",
    "type":"PLAY_SKELETON",
    "message":"스테이지 플레이 스켈레톤 전달",
    "data":{
        "userId":"d6b023a8-f502-4f1f-ae6c-a8383ec6e2a1",
        "playerNum":0,
        "frameNum":0,
        "skeleton":{
            "0":{
                "type":0,
                "x":91.0,
                "y":253.0,
                "z":395.12,
                "likelihood":0.99
            },
            "1":{
                "type":1,
                "x":91.0,
                "y":253.0,
                "z":395.12,
                "likelihood":0.99
            },
//...
            "32":{
                "type":32,
                "x":91.0,
                "y":253.0,
                "z":395.12,
                "likelihood":0.99
            }
        }
    }
}
----
'''

NOTE: 관절 인덱스 번호

- 서버 버전
----
NOSE = "0";
Left {
    EYE_INNER = "1";
    EYE = "2";
    EYE_OUTER = "3";

    EAR = "7";
    MOUTH = "9";
    SHOULDER = "11";
    ELBOW = "13";
    WRIST = "15";

    PINKY = "17";
    INDEX = "19";
    THUMB = "21";

    HIP = "23";
    KNEE = "25";
    ANKLE = "27";
    HEEL = "29";
    FOOT_INDEX = "31";
}

Right {
    EYE_INNER = "4";
    EYE = "5";
    EYE_OUTER = "6";

    EAR = "8";
    MOUTH = "10";
    SHOULDER = "12";
    ELBOW = "14";
    WRIST = "16";

    PINKY = "18";
    INDEX = "20";
    THUMB = "22";

    HIP = "24";
    KNEE = "26";
    ANKLE = "28";
    HEEL = "30";
    FOOT_INDEX = "32";
}
----

- 프론트 버전
0. nose,
1. leftEyeInner,
2. leftEye,
3. leftEyeOuter,
4. rightEyeInner,
5. rightEye,
6. rightEyeOuter,
7. leftEar,
8. rightEar,
9. leftMouth,
10. rightMouth,
11. leftShoulder,
12. rightShoulder,
13. leftElbow,
14. rightElbow,
15. leftWrist,
16. rightWrist,
17. leftPinky,
18. rightPinky,
19. leftIndex,
20. rightIndex,
21. leftThumb,
22. rightThumb,
23. leftHip,
24. rightHip,
25. leftKnee,
26. rightKnee,
27. leftAnkle,
28. rightAnkle,
29. leftHeel,
30. rightHeel,
31. leftFootIndex,
32. rightFootIndex