// 도메인 명 : h1
= COMMUNITY

// api 명 : h3
== *Video*
영상 커뮤니티 api




=== 영상 상세 조회

operation::get-video-detail[snippets='http-request,request-headers,path-parameters,response-fields-beneath-data,http-response']



=== 홈 영상 목록 조회 - 최신순

operation::get-video-list-by-created-at[snippets='http-request,request-parameters,response-fields-beneath-data,http-response']



=== 랜덤 영상 목록 조회 (검색 화면)

operation::get-video-list-by-random[snippets='http-request,request-parameters,response-fields-beneath-data,http-response']



=== 영상 삭제

operation::delete-video[snippets='http-request,path-parameters,response-fields-beneath-data,http-response']



=== 영상 업로드
operation::post-video-upload[snippets='http-request,request-headers,request-parts,request-parameters,response-fields-beneath-data,http-response']



=== 검색 - 태그 검색

operation::search-video-list-by-hasthag[snippets='http-request,request-parameters,response-fields-beneath-data-video-list,http-response']

'''
include::Comment-API.adoc[]
'''
include::Like-API.adoc[]


