
// api 명 : h3
== *Send Chat Message*
채팅 메세지 전송

- URL : `/app/chats/messages`

NOTE: 채팅 전송 푸시 알림 시 전달되는 데이터 명세가 맨 아래에 추가되었습니다. +
현재는 채팅방에 들어와있는 사람에게도 푸시알림이 옵니다.


==== Request header
|===
|필드명|타입|필수여부|제약조건|설명
|`+x-access-token+`
|`+String+`
|true
|JWT 형식
|액세스 토큰
|===

==== Request fields
|===
|필드명|타입|필수여부|제약조건|설명
|`+chatRoomId+`
|`+UUID+`
|true
|공백 불가
|메세지를 전송할 체팅방 식별자
|`+content+`
|`+String+`
|true
|공백 불가
|전송 메세지 내용
|===

==== Request body
[source,options="wrap"]
----
$ _INFO_:send STOMP message, destination = /app/chats/messages, content =
{
    "chatRoomId" : "9eb7a465-2c3d-4ceb-89a8-1f037da5a6a0",
    "content" : "출발~~"
},
header = {"x-access-token" : "eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJkNmIwMjNhOC1mNTAyLTRmMWYtYWU2Yy1hODM4M2VjNmUyYTEiLCJyb2xlcyI6WyJST0xFX1VTRVIiXSwiaWF0IjoxNjkyMDgxMDQ3LCJleHAiOjE2OTIwODQ2NDd9.pyS-tTkjsIQh0c6NMyBBrnGEVCqZVN-5CceziaoppC4"}
----

==== Response fields
|===
|필드명|타입|필수여부|설명
|`+timeStamp+`
|`+LocalDateTime+`
|true
|응답 시각
|`+type+`
|`+String+`
|true
|소켓 통신 유형. 고정값(CHAT_MESSAGE)
|`+data.createdAt+`
|`+LocalDateTime+`
|true
|메세지 전송 시각
|`+data.sender.userId+`
|`+String+`
|true
|보낸 사용자 고유값
|`+data.sender.nickname+`
|`+String+`
|true
|보낸 사용자 닉네임
|`+data.sender.profileImg+`
|`+String+`
|false
|보낸 사용자 프로필 사진
|`+data.content+`
|`+String+`
|true
|메세지 내용
|===

==== Response body
[source,http,options="nowrap"]
----
$ _INFO_:Receive subscribed message from destination /topic/chats/rooms/127e3afb-a0da-4082-8efe-af7c68ec92d4, content = MESSAGE
content-length:274
message-id:4675cccd-600d-320b-53d5-9ba5505fcd09-1
subscription:sub-0
content-type:application/json
destination:/topic/chats/rooms/127e3afb-a0da-4082-8efe-af7c68ec92d4
content-length:274

{
    "timeStamp":"2023/08/15 17:04:51",
    "type":"CHAT_MESSAGE",
    "message":"채팅 메세지 전송",
    "data":{
        "createdAt":"2023/08/15 17:04:51",
        "sender":{
            "userId":"d6b023a8-f502-4f1f-ae6c-a8383ec6e2a1",
            "nickname":"user_1",
            "profileImg":null
        },
        "content":"아이스크림 좋아좋아"
    }
}

----


==== Push Notification fields

푸시알림 시 전달되는 데이터 정보

|===
|전달방식|필드명|타입|필수여부|설명
|title
|`+-+`
|`+String+`
|true
|보낸 사용자 닉네임
|content
|`+-+`
|`+String+`
|true
|메세지 내용
|data
|`+type+`
|`+String+`
|true
|알림 유형. 고정값(SEND_CHAT_MESSAGE)
|data
|`+chatRoomId+`
|`+UUID+`
|true
|메세지가 보내진 채팅방의 고유값
|===
